[package]
authors = ["Chris West (Faux) <git@goeswhere.com>"]
name = "gpgv"
version = "0.1.0"

[dependencies]
base64 = "0.7"
byteorder = "1.1"
digest = "0.6"
error-chain = "0.11"
hex = "0.2"
rust-gmp = "0.5"
sha2 = "0.6"

[dependencies.sha-1]
features = ["generic"]
version = "0.4"
