[package]
authors = ["Chris West (Faux) <git@goeswhere.com>"]
name = "gpgrv"
version = "0.1.0"

[dependencies]
base64 = "0.7"
byteorder = "1.1"
digest = "0.6"
error-chain = "0.11"
sha2 = "0.6"

[dependencies.num-bigint]
git = "https://github.com/rust-num/num/"
rev = "a203e9f9fc438d05007fe65fd59581fc4c8b2dff"

[dependencies.sha-1]
features = ["generic"]
version = "0.4"

[dev-dependencies]
clap = "2.27"

[profile.release]
lto = true
