[package]
authors = ["Chris West (Faux) <git@goeswhere.com>"]
name = "gpgrv"
version = "0.1.0"

[dependencies]
base64 = "0.9"
byteorder = "1.2"
digest = "0.7"
error-chain = "0.12"
hex = "0.3"
iowrap = "0.1"
num = "0.2"
sha-1 = "0.7"
sha2 = "0.7"

[dev-dependencies]
clap = "2"
iowrap = "0.1"
tempfile = "3"

[profile.release]
lto = true
