[package]
authors = ["Chris West (Faux) <git@goeswhere.com>"]
categories = [
    "authentication",
    "cryptography",
    "parsing",
]
name = "gpgrv"
license = "MIT OR Apache-2.0"
readme = "README.md"
repository = "https://github.com/FauxFaux/gpgrv"
version = "0.1.0"

[badges.travis-ci]
repository = "FauxFaux/gpgrv"

[dependencies]
base64 = "0.9"
byteorder = "1.2"
digest = "0.7"
failure = "0.1"
hex = "0.3"
iowrap = "0.1"
num = "0.2"
sha-1 = "0.7"
sha2 = "0.7"

[dev-dependencies]
clap = "2"
iowrap = "0.1"
tempfile = "3"

[profile.release]
lto = true
