[package]
authors = ["Chris West (Faux) <git@goeswhere.com>"]
name = "gpgrv"
version = "0.1.0"

[dependencies]
base64 = "0"
byteorder = "1"
digest = "0.6"
error-chain = "0.11"
hex = "0.3"
iowrap = "0"
num = "0.2"
sha2 = "0.6"

[dependencies.sha-1]
features = ["generic"]
version = "0.4"

[dev-dependencies]
clap = "2"
iowrap = "0"
tempfile = "2"

[profile.release]
lto = true
