[package]
authors = ["Chris West (Faux) <git@goeswhere.com>"]
categories = [
    "authentication",
    "cryptography",
    "parsing",
]
description = "Pure-Rust implementation of gpgv, to verify gpg signatures"
name = "gpgrv"
license = "MIT OR Apache-2.0"
readme = "README.md"
repository = "https://github.com/FauxFaux/gpgrv"
version = "0.2.0"

edition = "2018"

[badges.travis-ci]
repository = "FauxFaux/gpgrv"

[dependencies]
base64 = "0.10"
byteorder = "1"
cast = "0.2"
digest = "0.8"
failure = "0.1"
hex = "0.3"
iowrap = "0.2"
libflate = "0.1"
memchr = "2"
num = "0.2"
sha-1 = "0.8"
sha2 = "0.8"

[dev-dependencies]
clap = "2"
tempfile = "3"

[profile.release]
lto = true
